# Generated by Django 5.2.8 on 2025-11-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllisting',
            name='price_timecredits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('TC', 'Time Credits'), ('UPI', 'UPI')], default='UPI', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
