# Generated by Django 5.1.3 on 2025-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
