# Generated by Django 5.1.3 on 2025-11-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_time_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction'),
        ),
    ]
