# Generated by Django 5.1.3 on 2025-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatroom_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
