# Generated by Django 5.1.3 on 2025-11-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_chatroom_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('TC', 'Time Credits'), ('UPI', 'UPI'), ('EX', 'Exchange Skills')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
